<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slavlee_cookie_control"
 *
 * Auto generated by Extension Builder 2020-10-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Slavlee Cookie Control (Free Version)',
    'description' => 'This extensions shows an alert message, where users can accept to use cookies. If they are disagree, then all cookies will be deleted.
This cookie gives you the opportunity to comply to the latest European Privacy Protection Law. The pro version is available on https://codecanyon.net/item/slavlee-cookie-control/21914103.',
    'category' => 'plugin',
    'author' => 'Kevin Chileong Lee',
    'author_email' => 'info@slavlee.de',
    'state' => 'stable',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.10 Free',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.32-10.4.99',
        	'php' => '7.2.0-7.9.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
